### ISSUE TITLE
"getIntList" simple does not work

### ISSUE THREAD

**Issue by Rexee** [tushar-acharya/PrefCompat#5]
```java
ArrayList<Integer> list = new ArrayList<>();
list.add(1);
Pref.putIntList("test", list);

Log.d("DBG", "List =" + Pref.getIntList("test").toString());
```
Error:
_W/System.err: java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.Integer;_

**How you even release this feature?!**

**Comment by tushar-acharya** [comment]
This is fixed with #6
