### ISSUE TITLE
MODE_WORLD_WRITEABLE

### ISSUE THREAD

**Issue by croccio** [tushar-acharya/PrefCompat#7]
Can you set a config to make preferences WORLD_READABLE? And init Prefs from another appid? 

I would do like something this:

Context myContext = createPackageContext("com.example", 
Context.MODE_WORLD_WRITEABLE); // where com.example is the owning  app containing the preferences
  SharedPreferences testPrefs = myContext.getSharedPreferences 
("test_prefs", Context.MODE_WORLD_WRITEABLE);

**Comment by tushar-acharya** [comment]
MODE_WORLD_WRITEABLE is deprecated
